### ISSUE TITLE
Atom colour issue

### ISSUE THREAD

**Issue by jen-power** [jen-power/contact-list-generator#1]
@thomasjbradley

https://vimeo.com/425893715

Have you ever come across this issue? I have a Syntax Theme set in Atom so that different elements will be coloured — which works fine, even within .js files — but as soon as I'm about to finish closing my `script` tag in an HTML document, all the colour disappears.

**Comment by thomasjbradley** [comment]
Wow. That’s totally weird. I have not run into that problem before.
Do you have all the packages up-to-date?

**Comment by jen-power** [comment]
I believe so, they usually auto-update but I ran the update again and it's still happening when I make new HTML files. It's not the end of the world, the code still works, it's just rather annoying.
